apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-service
  namespace: voip
  labels:
    component: voice-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: voice-service
  template:
    metadata:
      labels:
        component: voice-service
    spec:
      containers:
        - name: app
          image: cycoresystems/asterisk-demo-voice-ari
          env:
            - name: NATS_URI
              value: nats://nats:4222
---

apiVersion: v1
kind: Service
metadata:
  name: audiosocket
  namespace: voip
  labels:
    component: audiosocket
spec:
  selector:
    component: audiosocket
  ports:
  - name: audiosocket
    port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiosocket
  namespace: voip
  labels:
    component: audiosocket
spec:
  replicas: 1
  selector:
    matchLabels:
      component: audiosocket
  template:
    metadata:
      labels:
        component: audiosocket
    spec:
      containers:
        - name: audiosocket
          image: cycoresystems/astricon-voice-service
          ports:
            - name: audiosocket
              containerPort: 8080
