apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: voip
  labels:
    component: nats
spec:
  selector:
    component: nats
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: voip
  labels:
    component: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nats
  template:
    metadata:
      labels:
        component: nats
    spec:
      containers:
      - name: gnatsd
        image: nats
        ports:
        - containerPort: 4222 
          name: client
        - containerPort: 6222 
          name: cluster
        - containerPort: 8222 
          name: monitor
        livenessProbe:
          tcpSocket:
            port: 8222
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8222
          initialDelaySeconds: 15
          timeoutSeconds: 5
        resources:
          requests:
            cpu: "0.1"
