apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    component: app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: app
          image: cycoresystems/scaling-ari-app
          env:
            - name: NATS_URI
              value: nats://nats:4222
