apiVersion: v1
kind: Service
metadata:
  name: asterisk
  namespace: voip
spec:
  selector:
    component: asterisk
  ports:
    - name: sip
      protocol: UDP
      port: 5060

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: asterisk
  namespace: voip
  labels:
    component: asterisk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: asterisk
    spec:
      volumes:
        - name: config
          emptyDir: {}
        - name: custom
          secret:
            secretName: asterisk-config
      containers:
        - name: asterisk
          image: cycoresystems/asterisk
          volumeMounts:
            - name: config
              mountPath: /etc/asterisk
        - name: config
          image: cycoresystems/asterisk-config
          volumeMounts:
            - name: config
              mountPath: /etc/asterisk
            - name: custom
              mountPath: /source
          env:
            - name: CLOUD
              value: gcp
            - name: ARI_APPLICATION
              value: demo
            - name: ARI_USERNAME
              value: admin
            - name: ARI_PASSWORD
              value: admin
        - name: natsgw
          image: cycoresystems/ari-proxy:v2.4
          env:
            - name: NATS_URI
              value: nats://nats:4222
            - name: ARI_APPLICATION
              value: demo
            - name: ARI_USERNAME
              value: admin
            - name: ARI_PASSWORD
              value: admin
