apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-service
  namespace: voip
  labels:
    component: voice-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: voice-service
  template:
    metadata:
      labels:
        component: voice-service
    spec:
      containers:
        - name: app
          image: cycoresystems/asterisk-demo-voice-ari
          env:
            - name: NATS_URI
              value: nats://nats:4222
